name: Test Pull Request (Java)

on:
  merge_group:
  pull_request:
    branches:
    - main
    paths:
    - 'java/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Discover changed paths
      id: paths
      run: |
        env
        echo "a PR was triggered; let's find out which modules were updated"
        # see: https://stackoverflow.com/a/8721550/24069 for usage of paste
        echo "changed_java_projects=$( git diff --name-only --merge-base origin/$GITHUB_BASE_REF $GITHUB_SHA  | xargs -n 1 dirname | uniq | grep -v "^\." | paste -s -d, -)" >> $GITHUB_OUTPUT
        echo "These are the modules that we'll work with: $(cat $GITHUB_OUTPUT)"

    - name: Test Java Samples
      run: |
        env
        echo  ${{ steps.paths.outputs.changed_java_projects }}

#        ./scripts/smoke.sh --suite java \
#                           --builder paketobuildpacks/builder:full \
#                           --builder paketobuildpacks/builder:base \
#                           --builder paketobuildpacks/builder:tiny
